### ISSUE TITLE
Mobile Menu Does not work 

### ISSUE THREAD

**Issue by damienwebdev** [mage-os/devdocs-website#12]
![Screenshot_20230705-183052.png](https://github.com/mage-os/devdocs-website/assets/9029654/1df7910c-d4b8-4063-9a6d-ed6f0f3ea09a)

**Comment by DavidLambauer** [comment]
Can't confirm that. Tested it with my iPhone. Could you verify again?

**Comment by damienwebdev** [comment]
Works now.
