### ISSUE TITLE
Fix Meta Tags

### ISSUE THREAD

**Issue by DavidLambauer** [mage-os/devdocs-website#19]
Currently, there are no meta tags or schema.org/social tags for the site. Ideally, we don't have to manage those manually. The task for this issue is to come up with a concept of how we can easily manage the necessary meta tags without manually adding them everywhere.

**Comment by DavidLambauer** [comment]
In other issues (https://github.com/mage-os/devdocs-website/issues/6), we try to work with more Commonmark Extension (https://commonmark.thephpleague.com/2.4/extensions/mentions/). We could use these extensions to maintain Keywords, Descriptions, and Schema.org Tags in a markdown file. 

We should be able to maintain the meta tags per page...

**Comment by nikolalardev** [comment]
Please assign it to me.

**Comment by nikolalardev** [comment]
Please review it https://github.com/mage-os/devdocs-website/pull/59
