### ISSUE TITLE
DevDocs Broken

### ISSUE THREAD

**Issue by sprankhub** [mage-os/devdocs-website#21]
Since merging https://github.com/mage-os/devdocs-website/pull/16, it looks like the devdocs are broken - or at least the deployment: https://github.com/mage-os/devdocs-website/actions

Currently devdocs are down:

![image](https://github.com/mage-os/devdocs-website/assets/930199/07f6ed32-1fa0-4ab7-a221-87a4ca09aa77)

@DavidLambauer, could you have a look?

**Comment by DavidLambauer** [comment]
Done done. Will provide a proper fix once I’m back from vacation. Maxcluster knows about the issue and a workaround is in place

David Lambauer +49 176 66 890 102 ( tel:+4917666890102 ) Geschäftsführer / CEO run-as-root.sh ( https://run-as-root.sh/ )

Sent via Superhuman iOS ( ***@***.*** )

**Comment by jonashrem** [comment]
Should the phone number really stand there?
