### ISSUE TITLE
Small feedback

### ISSUE THREAD

**Issue by jellesiderius** [mage-os/devdocs-website#24]
Awesome work on the devdocs guys! I got two small feedback points.

### Darkmode
When reading code blocks, the dark mode hides the text.

![Screenshot 2023-08-22 at 09 48 06](https://github.com/mage-os/devdocs-website/assets/8039493/60a04971-c974-46c2-b39b-0c7939bcc79b)

**Comment by DavidLambauer** [comment]
Thank you @jellesiderius, I'll check on that. Not entirely sure what causes that, but I'll figure it out
