### ISSUE TITLE
Add a note to sites that haven't been reviewed, yet.

### ISSUE THREAD

**Issue by DavidLambauer** [mage-os/devdocs-website#31]
The devdocs are freshly generated, and only a few parts have been reviewed by real humans. It might make sense to tell the user about this and also encourage them to review the pages themselves.

**Comment by dermatz** [comment]
Can be solved with a little badge. 
But is it possible to solve it programmatically?

**Comment by DavidLambauer** [comment]
I added the community note, which is now on all pages. I guess, it's a manual process going through the docs and review them one by one.
