### ISSUE TITLE
[BUG] The theme switcher jumps places when switching themes

### ISSUE THREAD

**Issue by damienwebdev** [mage-os/devdocs-website#37]
![image](https://github.com/mage-os/devdocs-website/assets/9029654/451b5f52-3fce-4d18-a50d-a9d5dd665386)
![image](https://github.com/mage-os/devdocs-website/assets/9029654/7c30c741-8940-4ca0-aa79-b794bd71e3c4)
![image](https://github.com/mage-os/devdocs-website/assets/9029654/ea52007c-ad24-4d87-8e93-9a83cd0b89ca)

**Comment by nikolalardev** [comment]
I am working on it.

**Comment by nikolalardev** [comment]
Fixed, and ready for code review https://github.com/mage-os/devdocs-website/pull/40

**Comment by DavidLambauer** [comment]
gg
