### ISSUE TITLE
Sticky scroll navigation

### ISSUE THREAD

**Issue by Morgy93** [mage-os/devdocs-website#42]
The navigation on the left side should be sticky while scrolling so that you have access to it all the time.

<img width="442" alt="image" src="https://github.com/mage-os/devdocs-website/assets/7961978/7fd1e254-697e-41b3-90bf-2b4b1ff9cba7">

Example: https://docusaurus.io/docs/styling-layout (just scroll down if the page is wide enough to show the left side navigation)

Currently you lose focus quickly if you scroll down on pages like https://devdocs.mage-os.org/docs/main/overview-of-magento-2-development#models

**Comment by DavidLambauer** [comment]
The navigation grows enormously when you open specific trees. Having it sticky would mean different scrollable divs, which I dislike. You can press pageup/pagedown on your keyboard. 

![CleanShot 2023-09-26 at 15 43 41](https://github.com/mage-os/devdocs-website/assets/1841317/99d56206-51dc-4868-ba95-eba207f4dc18)

**Comment by DavidLambauer** [comment]
To be clear. I love the idea of having a site where you can focus on the content in its purest form. No distractions, nothing to click on. Just read the docs, nothing else...

![CleanShot 2023-09-26 at 15 47 51](https://github.com/mage-os/devdocs-website/assets/1841317/791c118e-8c0f-4170-bb66-a0bdf79aa132)
