### ISSUE TITLE
Scroll to top button

### ISSUE THREAD

**Issue by Morgy93** [mage-os/devdocs-website#43]
Currently you must scroll all the way to the top manually to reach the navigation (fixed by #42) or the search bar.

A little "scroll to top" button would enhance usability.

<img width="100" alt="image" src="https://github.com/mage-os/devdocs-website/assets/7961978/a5d7b698-6634-4483-9456-d124d34b505f">

Example: https://docusaurus.io/docs/styling-layout (scroll down and a little bit up to show the icon on the bottom right)

**Comment by DavidLambauer** [comment]
Although this seems like a good idea to implement, I highly doubt anyone clicks that button. I prefer not to do it because it adds visual noise to the site with little value.

**Comment by dermatz** [comment]
@DavidLambauer - but you don't give the user another possibility to scroll up. This is sadly not user-friendly. I can recommend to you to be sure users can easily navigate to the top. Think about it - change header to sticky or add a fixed footer nav or add this tiny button. The current navigation is horrible. Also think to people with disabilities.

**Comment by DavidLambauer** [comment]
You have a HOME button on your keyboard. That's how you go up.

**Comment by DavidLambauer** [comment]
For clarity, my perspective hinges on embracing minimalistic design principles and being cognizant of cognitive load. The inclusion of a back-to-top button, in my view, adds unnecessary clutter without significant benefits. Native solutions already exist for this functionality, both for desktop and mobile users, rendering the button redundant.

Research in usability highlights the risks of adding superfluous features to web interfaces. These additions can heighten cognitive load, complicating navigation and usage for users. Overly complex or unclear interfaces can negatively impact user experience, diverting users from their primary objectives.

Reference: Nielsen, J. (2000). Designing web usability: The practice of simplicity. New Riders Publishing.

Prioritizing minimalistic design in web development means stripping away the extraneous and spotlighting the fundamental. Such design naturally reduces cognitive load, ensuring users stay focused and enjoy a streamlined experience. Effective minimalistic design strikes a balance, being both visually appealing and operationally seamless.

Reference: Krug, S. (2014). Don't make me think, revisited: A common sense approach to web usability. New Riders Publishing.
