### ISSUE TITLE
(Sticky) page overview

### ISSUE THREAD

**Issue by Morgy93** [mage-os/devdocs-website#44]
Currently there is no overview about the sections of the page while you're scrolling / reading on a page.

It would be great if there is a sticky overview where you can keep track of the page and where you are at all the time.

Example: https://docusaurus.io/docs/styling-layout

<img width="1317" alt="image" src="https://github.com/mage-os/devdocs-website/assets/7961978/c36bf683-fc2c-4196-bb4f-830a52890293">

**Comment by DavidLambauer** [comment]
Another example here: https://syntax.tailwindui.com/

**Comment by DavidLambauer** [comment]
I am unsure about this feature tbh. It adds another column to the visual page layout. I am very biased with this change, as it "destroys" the minimal approach a bit 🙈 . @laurali123, could you maybe create a mockup for us?

**Comment by laurali123** [comment]
@DavidLambauer @Morgy93 
I took the sticky overview from docusaurus as an example. What about putting the overview at the bottom of the page? That will keep the page "clean" and as the users already have an agenda at the top of the page, we'll offer them additionally at the end of the page (the place where you get to after reading the documentation) the opportunity to check in which part of the agenda you currently are:

<img width="1259" alt="image" src="https://github.com/mage-os/devdocs-website/assets/24475376/92726158-4e5a-44e7-a9ee-ac6b095ec6d8">

<img width="1385" alt="image" src="https://github.com/mage-os/devdocs-website/assets/24475376/eb20430c-ab16-4d5a-9286-1f850df2d530">

**Comment by DavidLambauer** [comment]
Thank you @laurali123 ! I'm not yet convinced, though 😆. I will leave this issue open for a while and get back to it.

**Comment by Morgy93** [comment]
Sadly https://github.com/mage-os/devdocs-website/issues/42 was rejected, otherwise it could be bundled together:

<img width="990" alt="image" src="https://github.com/mage-os/devdocs-website/assets/7961978/71dabdf1-9288-4961-9870-62300cc6b1ed">

Source: https://bun.sh/docs/templates#from-github (Just scroll through the page)

**Comment by DavidLambauer** [comment]
I appreciate your suggestions and it is nice to see what other systems do. I want to stick with a page that is focused on the content with a minimal design. Additional tables or sticky navigations are nice-to-have features that work against that approach.
