### ISSUE TITLE
Broken search

### ISSUE THREAD

**Issue by Morgy93** [mage-os/devdocs-website#46]
For whatever reason the search is broken for me currently:

<img width="639" alt="image" src="https://github.com/mage-os/devdocs-website/assets/7961978/a083bf4b-a98f-4d45-b455-4138655f4e0d">

**Comment by DavidLambauer** [comment]
huh, true. We're using the Algolia Crawler / Algolia Docsearch. The Crawler seems to have changed and doesn't parse the paragraphs correctly. Will dig into it

**Comment by DavidLambauer** [comment]
I resetted the latest crawl configs. Let's see if that helped...

**Comment by DavidLambauer** [comment]
fixed
