### ISSUE TITLE
a11y: No visible indicator for parent/child menu elements

### ISSUE THREAD

**Issue by dermatz** [mage-os/devdocs-website#50]
![image](https://github.com/mage-os/devdocs-website/assets/6103201/f818f054-7fe9-4666-b5f7-83687474e438)

In the menu, it is no visual indicator which elements have children.

**Comment by DavidLambauer** [comment]
Good point. In fact, they all have children, so is an additional indicator then necessary? 🤔

**Comment by dermatz** [comment]
i think yes. First time user don't know it
